/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Pc
 */
public class frame extends javax.swing.JFrame {

    /**
     * Creates new form frame
     */
    Connection conn=null; PreparedStatement pst=null; ResultSet rs=null;
    int columnsNumber=0;
    public frame() {
        initComponents();
        retrievetable(jTablearac,"SELECT * FROM ARAC");
        retrievetable(jTableuye1,"SELECT * FROM UYELER");
        retrievetable(jTablecalisan,"SELECT * FROM CALISAN");
        txt_id.setEnabled(false);
        txt_id2.setEnabled(false);
        txt_calisanID.setEnabled(false);
                
    }

    private void retrievetable(javax.swing.JTable jTable, String sql){
        try
        {
            DefaultTableModel tbl=(DefaultTableModel) jTable.getModel();
            while(tbl.getRowCount()>0){
                tbl.removeRow(0);
            }
            conn=db.connet_db();
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            ResultSetMetaData rsmd=rs.getMetaData();
            columnsNumber=rsmd.getColumnCount();
            
            String[] data=new String[columnsNumber];
            while(rs.next()){
                for (int i = 0; i < data.length; i++) {
                    data[i]=rs.getString(i+1);    
                }
                DefaultTableModel tblmodel=(DefaultTableModel) jTable.getModel();
                tblmodel.addRow(data);
            }
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, ex);
        }   
        finally{
            try
            {
                conn.close();
            }
            catch(Exception ex)
            {
                
            }    
        }
    }
    
    private void txtresetle()
    {
        txt_id.setText("");txt_marka.setText("");txt_model.setText("");
        txt_vitestipi.setText("");txt_yakittipi.setText("");txt_durum.setText("");txt_kategori.setText("");
        txt_id2.setText(""); txt_adsoyad.setText("");txt_email.setText("");txt_adres.setText("");
        txt_tel.setText("");txt_tel2.setText("");txt_ehliyetyil.setText("");
        txt_calisanID.setText(""); txt_adsoyad1.setText("");txt_mail.setText("");txt_kullaniciad.setText("");
        txt_sifre.setText("");txt_unvanid.setText("");txt_telno.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTablearac = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btn_guncelle = new javax.swing.JButton();
        btn_sil = new javax.swing.JButton();
        btn_yenikayit = new javax.swing.JButton();
        btn_kaydet = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_marka = new javax.swing.JTextField();
        txt_model = new javax.swing.JTextField();
        txt_vitestipi = new javax.swing.JTextField();
        txt_id = new javax.swing.JTextField();
        txt_yakittipi = new javax.swing.JTextField();
        txt_durum = new javax.swing.JTextField();
        txt_kategori = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableuye1 = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        lbl_adres = new javax.swing.JLabel();
        lbl_id = new javax.swing.JLabel();
        lbl_email = new javax.swing.JLabel();
        lbl_ehliyetyil = new javax.swing.JLabel();
        lbl_adsoyad = new javax.swing.JLabel();
        lbl_tel = new javax.swing.JLabel();
        lbl_tel2 = new javax.swing.JLabel();
        txt_adsoyad = new javax.swing.JTextField();
        txt_id2 = new javax.swing.JTextField();
        txt_tel2 = new javax.swing.JTextField();
        txt_ehliyetyil = new javax.swing.JTextField();
        txt_tel = new javax.swing.JTextField();
        txt_adres = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        btn_kaydet1 = new javax.swing.JButton();
        btn_yenikayit1 = new javax.swing.JButton();
        btn_sil1 = new javax.swing.JButton();
        btn_guncelle1 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablecalisan = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_calisanID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_adsoyad1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txt_mail = new javax.swing.JTextField();
        btn_sil2 = new javax.swing.JButton();
        btn_güncelle2 = new javax.swing.JButton();
        btn_kaydet2 = new javax.swing.JButton();
        btn_yenikayıt2 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txt_kullaniciad = new javax.swing.JTextField();
        txt_sifre = new javax.swing.JTextField();
        txt_unvanid = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txt_telno = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTablearac.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jTablearac.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTablearac.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ARAC_ID", "MARKA", "MODEL", "VITES_AD", "YAKIT_AD", "DURUM", "KATEGORI_ID"
            }
        ));
        jTablearac.setCellSelectionEnabled(true);
        jTablearac.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablearacMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTablearac);
        jTablearac.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("ARAÇ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("MODEL:");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("MARKA:");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("YAKIT TİPİ:");
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("VİTES TİPİ:");
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("KATEGORİ:");
        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btn_guncelle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_guncelle.setText("GÜNCELLE");
        btn_guncelle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_guncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guncelleActionPerformed(evt);
            }
        });

        btn_sil.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_sil.setText("SİL");
        btn_sil.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_sil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_silActionPerformed(evt);
            }
        });

        btn_yenikayit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_yenikayit.setText("YENİ KAYIT");
        btn_yenikayit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_yenikayit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_yenikayitActionPerformed(evt);
            }
        });

        btn_kaydet.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_kaydet.setText("KAYDET");
        btn_kaydet.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_kaydet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kaydetActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("ID:");
        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("DURUM:");
        jLabel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txt_marka.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_marka.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_marka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_markaActionPerformed(evt);
            }
        });

        txt_model.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_model.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_model.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_modelActionPerformed(evt);
            }
        });

        txt_vitestipi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_vitestipi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_vitestipi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_vitestipiActionPerformed(evt);
            }
        });

        txt_id.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_id.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idActionPerformed(evt);
            }
        });

        txt_yakittipi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_yakittipi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_yakittipi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_yakittipiActionPerformed(evt);
            }
        });

        txt_durum.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_durum.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_durum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_durumActionPerformed(evt);
            }
        });

        txt_kategori.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_kategori.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/empoleye/icons8-back-arrow-50.png"))); // NOI18N
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_vitestipi, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_model, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_marka, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(54, 54, 54)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_yakittipi, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                    .addComponent(txt_durum, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                    .addComponent(txt_kategori))
                .addContainerGap(138, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_kaydet, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(113, 113, 113)
                .addComponent(btn_yenikayit, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(107, 107, 107)
                .addComponent(btn_sil, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93)
                .addComponent(btn_guncelle, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btn_guncelle, btn_kaydet, btn_sil, btn_yenikayit});

        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_id, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_marka, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_model, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_vitestipi, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_yakittipi, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_kategori, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_durum, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(59, 59, 59)))))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_kaydet, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_yenikayit, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_sil, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_guncelle, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btn_guncelle, btn_kaydet, btn_sil, btn_yenikayit});

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane2)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("ARAÇ KAYIT", jPanel1);

        jTableuye1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTableuye1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "UYE_ID", "AD_SOYAD", "E_MAIL", "ADRES", "TELEFON", "TELEFON2", "EHLIYET_ALMA_YILI"
            }
        ));
        jTableuye1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableuye1MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jTableuye1);

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel17.setText("UYE");

        lbl_adres.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_adres.setText("ADRES");
        lbl_adres.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbl_id.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_id.setText("ID");
        lbl_id.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbl_email.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_email.setText("E MAIL");
        lbl_email.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbl_ehliyetyil.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_ehliyetyil.setText("EHLIYET ALMA YILI");
        lbl_ehliyetyil.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbl_adsoyad.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_adsoyad.setText("AD SOYAD");
        lbl_adsoyad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbl_tel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_tel.setText("TELEFON");
        lbl_tel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbl_tel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_tel2.setText("TELEFON 2");
        lbl_tel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txt_adsoyad.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_adsoyad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_adsoyad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_adsoyadActionPerformed(evt);
            }
        });

        txt_id2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_id2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_id2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_id2ActionPerformed(evt);
            }
        });

        txt_tel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_tel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_tel2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_tel2ActionPerformed(evt);
            }
        });

        txt_ehliyetyil.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_ehliyetyil.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_ehliyetyil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ehliyetyilActionPerformed(evt);
            }
        });

        txt_tel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_tel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_tel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_telActionPerformed(evt);
            }
        });

        txt_adres.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_adres.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_adres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_adresActionPerformed(evt);
            }
        });

        txt_email.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_email.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_emailActionPerformed(evt);
            }
        });

        btn_kaydet1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_kaydet1.setText("KAYDET");
        btn_kaydet1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_kaydet1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kaydet1ActionPerformed(evt);
            }
        });

        btn_yenikayit1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_yenikayit1.setText("YENİ KAYIT");
        btn_yenikayit1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_yenikayit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_yenikayit1ActionPerformed(evt);
            }
        });

        btn_sil1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_sil1.setText("SİL");
        btn_sil1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_sil1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sil1ActionPerformed(evt);
            }
        });

        btn_guncelle1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_guncelle1.setText("GÜNCELLE");
        btn_guncelle1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_guncelle1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guncelle1ActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/empoleye/icons8-back-arrow-50.png"))); // NOI18N
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                                .addComponent(btn_kaydet1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(62, 62, 62)
                                .addComponent(btn_yenikayit1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(85, 85, 85)
                                .addComponent(btn_sil1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(75, 75, 75)
                                .addComponent(btn_guncelle1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                                .addComponent(lbl_adres, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                                .addComponent(txt_adres, javax.swing.GroupLayout.PREFERRED_SIZE, 822, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lbl_email, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lbl_adsoyad, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lbl_id, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(52, 52, 52)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_id2, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                                    .addComponent(txt_adsoyad)
                                    .addComponent(txt_email))
                                .addGap(125, 125, 125)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lbl_ehliyetyil, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_tel2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_tel, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(39, 39, 39)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txt_ehliyetyil, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_tel, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_tel2, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(11, 11, 11)))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        jPanel7Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lbl_adres, lbl_adsoyad, lbl_ehliyetyil, lbl_email, lbl_id, lbl_tel, lbl_tel2});

        jPanel7Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txt_ehliyetyil, txt_tel2});

        jPanel7Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btn_guncelle1, btn_kaydet1, btn_sil1, btn_yenikayit1});

        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_id, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                            .addComponent(txt_id2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_adsoyad, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_adsoyad, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_email, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_tel, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                            .addComponent(txt_tel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_tel2, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                            .addComponent(txt_tel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_ehliyetyil, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_ehliyetyil, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_adres, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_adres, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_kaydet1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_yenikayit1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_sil1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_guncelle1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        jPanel7Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lbl_adres, lbl_adsoyad, lbl_ehliyetyil, lbl_email, lbl_id, lbl_tel, lbl_tel2});

        jPanel7Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txt_adsoyad, txt_ehliyetyil, txt_email, txt_id2, txt_tel, txt_tel2});

        jPanel7Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btn_guncelle1, btn_kaydet1, btn_sil1, btn_yenikayit1});

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 1184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(121, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("ÜYE KAYIT", jPanel2);

        jPanel3.setPreferredSize(new java.awt.Dimension(1208, 730));

        jTablecalisan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTablecalisan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CALISAN_ID", "AD_SOYAD", "E-MAIL", "KULLANICI_ADI", "SIFRE", "UNVAN_ID", "TELEFON"
            }
        ));
        jTablecalisan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablecalisanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTablecalisan);

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("ÇALIŞAN_ID :");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txt_calisanID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_calisanID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("AD SOYAD:");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txt_adsoyad1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_adsoyad1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_adsoyad1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_adsoyad1ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("E-MAİL :");
        jLabel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txt_mail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_mail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btn_sil2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_sil2.setText("SİL");
        btn_sil2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_sil2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sil2ActionPerformed(evt);
            }
        });

        btn_güncelle2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_güncelle2.setText("GÜNCELLE");
        btn_güncelle2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_güncelle2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_güncelle2ActionPerformed(evt);
            }
        });

        btn_kaydet2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_kaydet2.setText("KAYDET");
        btn_kaydet2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_kaydet2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kaydet2ActionPerformed(evt);
            }
        });

        btn_yenikayıt2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_yenikayıt2.setText("YENİ KAYIT");
        btn_yenikayıt2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_yenikayıt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_yenikayıt2ActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("KULLANICI ADI :");
        jLabel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("ŞİFRE :");
        jLabel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("UNVAN ID:");
        jLabel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txt_kullaniciad.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_kullaniciad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txt_sifre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_sifre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txt_unvanid.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_unvanid.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setText("ÇALIŞAN");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("TELEFON:");
        jLabel16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txt_telno.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_telno.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/empoleye/icons8-back-arrow-50.png"))); // NOI18N
        jButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txt_telno, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addComponent(jLabel11)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 591, Short.MAX_VALUE))
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txt_adsoyad1, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE)
                                        .addComponent(txt_calisanID)
                                        .addComponent(txt_mail, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                                        .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(btn_kaydet2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(96, 96, 96)
                                .addComponent(btn_yenikayıt2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(107, 107, 107)
                                .addComponent(btn_sil2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(btn_güncelle2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(116, 116, 116)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txt_kullaniciad)
                                .addComponent(txt_sifre)
                                .addComponent(txt_unvanid, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(21, 21, 21))))
        );

        jPanel5Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btn_güncelle2, btn_kaydet2, btn_sil2, btn_yenikayıt2});

        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addGap(25, 25, 25)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_calisanID, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_adsoyad1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txt_mail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(txt_kullaniciad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txt_sifre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_unvanid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_telno, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btn_kaydet2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btn_yenikayıt2))
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btn_sil2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btn_güncelle2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanel5Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel12, jLabel13, jLabel14, jLabel15, jLabel2, txt_adsoyad1, txt_calisanID, txt_kullaniciad, txt_mail, txt_sifre, txt_unvanid});

        jPanel5Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btn_güncelle2, btn_kaydet2, btn_sil2, btn_yenikayıt2});

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1165, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        jTabbedPane1.addTab("ÇALIŞAN KAYIT", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1170, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 808, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTablearacMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablearacMouseClicked
        String[] data=new String[columnsNumber];
        for (int i = 0; i < data.length; i++) {
            data[i]=jTablearac.getValueAt(jTablearac.getSelectedRow(), i).toString();   
                  }
        txt_id.setText(data[0]);
        txt_marka.setText(data[1]);
        txt_model.setText(data[2]);
        txt_vitestipi.setText(data[3]);
        txt_yakittipi.setText(data[4]);
        txt_durum.setText(data[5]);
        txt_kategori.setText(data[6]);
    
       
    }//GEN-LAST:event_jTablearacMouseClicked
     private void jTableuyeMouseClicked(java.awt.event.MouseEvent evt) {                                        
        String[] data=new String[columnsNumber];
        for (int j = 0; j < data.length; j++) {
            data[j]=jTableuye1.getValueAt(jTableuye1.getSelectedRow(), j).toString();   
                  }
        txt_id2.setText(data[0]);
        txt_adsoyad.setText(data[1]);
        txt_email.setText(data[2]);
        txt_adres.setText(data[3]);
        txt_tel.setText(data[4]);
        txt_tel2.setText(data[5]);
        txt_ehliyetyil.setText(data[6]);
    
       
    }                                  
    
    private void txt_markaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_markaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_markaActionPerformed

    private void btn_kaydetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kaydetActionPerformed
        if((txt_id.getText()).equals("")){
            try
            {
                conn=db.connet_db();
                String sql="INSERT INTO ARAC(MARKA,MODEL,VITES_AD,YAKIT_AD,DURUM,KATEGORI_ID) VALUES(?,?,?,?,?,?)";
                pst=conn.prepareStatement(sql);
                pst.setString(1, txt_marka.getText());
                pst.setString(2, txt_model.getText());
                pst.setString(3, txt_vitestipi.getText());
                pst.setString(4, txt_yakittipi.getText());
                pst.setString(5, txt_durum.getText());
                pst.setString(6, txt_kategori.getText());
                pst.execute();
                retrievetable(jTablearac,"SELECT * FROM ARAC");
                txtresetle();

            }
            catch(Exception ex)
            {

            }
            finally
            {
                try
                {
                    conn.close();
                }
                catch(Exception ex)
                {

                }
            }
        }
    }//GEN-LAST:event_btn_kaydetActionPerformed

    private void txt_modelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_modelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_modelActionPerformed

    private void txt_vitestipiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_vitestipiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_vitestipiActionPerformed

    private void txt_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idActionPerformed

    private void txt_yakittipiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_yakittipiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_yakittipiActionPerformed

    private void txt_durumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_durumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_durumActionPerformed

    private void btn_silActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_silActionPerformed
        if(!(txt_id.getText()).equals("")){
            try
            {
                conn=db.connet_db();
                String sql="DELETE FROM ARAC WHERE ARAC_ID=?";
                pst=conn.prepareStatement(sql);
                pst.setString(1, txt_id.getText());
               pst.execute();
               retrievetable(jTablearac,"SELECT * FROM ARAC");
               txtresetle();
               JOptionPane.showMessageDialog(null, "Kayıt silinmiştir!");

            }
            catch(Exception ex)
            {
                 JOptionPane.showMessageDialog(null, ex);
            }

            
            finally
            {
                try
                {
                    conn.close();
                }
                catch(Exception ex)
                {

                }
            }}
         else{
    JOptionPane.showMessageDialog(null, "Lütfen silmek istediğiniz kaydı seçiniz!");
        }
    }//GEN-LAST:event_btn_silActionPerformed

    private void btn_guncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guncelleActionPerformed
         if(!(txt_id.getText()).equals("")){
            try
            {
                conn=db.connet_db();
                String sql="UPDATE ARAC SET MARKA=?, MODEL=?, VITES_AD=?, YAKIT_AD=?, DURUM=?, KATEGORI_ID=? WHERE ARAC_ID=?";
                pst=conn.prepareStatement(sql);
                pst.setString(1, txt_marka.getText());
                pst.setString(2, txt_model.getText());
                pst.setString(3, txt_vitestipi.getText());
                pst.setString(4, txt_yakittipi.getText());
                pst.setString(5, txt_durum.getText());
                pst.setString(6, txt_kategori.getText());
                pst.setString(7, txt_id.getText());
                pst.execute();
                retrievetable(jTablearac,"SELECT * FROM ARAC");
                 JOptionPane.showMessageDialog(null, "Kayıt başarıyla güncellenmiştir!");

            }
            catch(Exception ex)
            {
                JOptionPane.showMessageDialog(null, ex);

            }
            finally
            {
                try
                {
                    conn.close();
                }
                catch(Exception ex)
                {

                }
            }
        }
         else{
              JOptionPane.showMessageDialog(null, "Lütfen tablodan bir değer seçiniz!");
         }
    }//GEN-LAST:event_btn_guncelleActionPerformed

    private void btn_yenikayitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_yenikayitActionPerformed
       txtresetle();
    }//GEN-LAST:event_btn_yenikayitActionPerformed

    private void btn_kaydet2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kaydet2ActionPerformed
        if((txt_id.getText()).equals("")){
            try
            {
                conn=db.connet_db();
                String sql="INSERT INTO CALISAN(AD_SOYAD,E_MAIL,KULLANICI_ADI,SIFRE,UNVAN_ID,TELEFON) VALUES(?,?,?,?,?,?)";
                pst=conn.prepareStatement(sql);
                pst.setString(1, txt_adsoyad1.getText());
                pst.setString(2, txt_mail.getText());
                pst.setString(3, txt_kullaniciad.getText());
                pst.setString(4, txt_sifre.getText());
                pst.setString(5, txt_unvanid.getText());
                pst.setString(6, txt_telno.getText());
                pst.execute();
                retrievetable(jTablecalisan,"SELECT * FROM CALISAN");
                txtresetle();

            }
            catch(Exception ex)
            {

            }
            finally
            {
                try
                {
                    conn.close();
                }
                catch(Exception ex)
                {

                }
            }
        }
                                              

    }//GEN-LAST:event_btn_kaydet2ActionPerformed

    private void btn_yenikayıt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_yenikayıt2ActionPerformed
           txtresetle();

    }//GEN-LAST:event_btn_yenikayıt2ActionPerformed

    private void btn_sil2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sil2ActionPerformed
          if(!(txt_calisanID.getText()).equals("")){
            try
            {
                conn=db.connet_db();
                String sql="DELETE FROM CALISAN WHERE CALISAN_ID=?";
                pst=conn.prepareStatement(sql);
                pst.setString(1, txt_calisanID.getText());
               pst.execute();
               retrievetable(jTablecalisan,"SELECT * FROM CALISAN");
               txtresetle();
               JOptionPane.showMessageDialog(null, "Kayıt silinmiştir!");

            }
            catch(Exception ex)
            {
                 JOptionPane.showMessageDialog(null, ex);
            }

            
            finally
            {
                try
                {
                    conn.close();
                }
                catch(Exception ex)
                {

                }
            }}
         else{
              
    JOptionPane.showMessageDialog(null, "Lütfen silmek istediğiniz kaydı seçiniz!");
        }
                                          

    }//GEN-LAST:event_btn_sil2ActionPerformed

    private void btn_güncelle2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_güncelle2ActionPerformed
        if(!(txt_calisanID.getText()).equals("")){
            try
            {
                conn=db.connet_db();
                String sql="UPDATE CALISAN SET AD_SOYAD=? ,E_MAIL=? ,KULLANICI_ADI=? ,SIFRE=? ,UNVAN_ID=? ,TELEFON=? WHERE CALISAN_ID=?";
                pst=conn.prepareStatement(sql);
                pst.setString(1, txt_adsoyad1.getText());
                pst.setString(2, txt_mail.getText());
                pst.setString(3, txt_kullaniciad.getText());
                pst.setString(4, txt_sifre.getText());
                pst.setString(5, txt_unvanid.getText());
                pst.setString(6, txt_telno.getText());
                pst.setString(7, txt_calisanID.getText());
                pst.execute();
                retrievetable(jTablecalisan,"SELECT * FROM CALISAN");
                 JOptionPane.showMessageDialog(null, "Kayıt başarıyla güncellenmiştir!");

            }
            catch(Exception ex)
            {
                JOptionPane.showMessageDialog(null, ex);

            }
            finally
            {
                try
                {
                    conn.close();
                }
                catch(Exception ex)
                {

                }
            }
        }
         else{
              JOptionPane.showMessageDialog(null, "Lütfen tablodan bir değer seçiniz!");
         }
                                              

   
    }//GEN-LAST:event_btn_güncelle2ActionPerformed

    private void txt_adsoyad1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_adsoyad1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_adsoyad1ActionPerformed

    private void jTablecalisanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablecalisanMouseClicked
                                            
        String[] data=new String[columnsNumber];
        for (int j = 0; j < data.length; j++) {
            data[j]=jTablecalisan.getValueAt(jTablecalisan.getSelectedRow(), j).toString();   
                  }
        txt_calisanID.setText(data[0]);
        txt_adsoyad1.setText(data[1]);
        txt_mail.setText(data[2]);
        txt_kullaniciad.setText(data[3]);
        txt_sifre.setText(data[4]);
        txt_unvanid.setText(data[5]);
        txt_telno.setText(data[6]);
    
       
    
    }//GEN-LAST:event_jTablecalisanMouseClicked

    private void btn_guncelle1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guncelle1ActionPerformed
        if(!(txt_id2.getText()).equals("")){
            try
            {
                conn=db.connet_db();
                String sql="UPDATE UYELER SET  AD_SOYAD=?, E_MAIL=?, ADRES=?, TEL=?, TEL2=?, EHLIYET_YIL=? WHERE UYE_ID=?";
                pst=conn.prepareStatement(sql);
                pst.setString(1, txt_adsoyad.getText());
                pst.setString(2, txt_email.getText());
                pst.setString(3, txt_adres.getText());
                pst.setString(4, txt_tel.getText());
                pst.setString(5, txt_tel2.getText());
                pst.setString(6, txt_ehliyetyil.getText());
                pst.setString(7, txt_id2.getText());
                pst.execute();
                retrievetable(jTableuye1,"SELECT * FROM UYELER");
                JOptionPane.showMessageDialog(null, "Kayıt başarıyla güncellenmiştir!");

            }
            catch(Exception ex)
            {
                JOptionPane.showMessageDialog(null, ex);

            }
            finally
            {
                try
                {
                    conn.close();
                }
                catch(Exception ex)
                {

                }
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Lütfen tablodan bir değer seçiniz!");
        }
    }//GEN-LAST:event_btn_guncelle1ActionPerformed

    private void btn_sil1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sil1ActionPerformed
        if(!(txt_id2.getText()).equals("")){
            try
            {
                conn=db.connet_db();
                String sql="DELETE FROM UYELER WHERE UYE_ID=?";
                pst=conn.prepareStatement(sql);
                pst.setString(1, txt_id2.getText());
                pst.execute();
                retrievetable(jTableuye1,"SELECT * FROM UYELER");
                txtresetle();
                JOptionPane.showMessageDialog(null, "Kayıt silinmiştir!");

            }
            catch(Exception ex)
            {
                JOptionPane.showMessageDialog(null, ex);
            }

            finally
            {
                try
                {
                    conn.close();
                }
                catch(Exception ex)
                {

                }
            }}
            else{
                JOptionPane.showMessageDialog(null, "Lütfen silmek istediğiniz kaydı seçiniz!");
            }
    }//GEN-LAST:event_btn_sil1ActionPerformed

    private void btn_yenikayit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_yenikayit1ActionPerformed
        txtresetle();
    }//GEN-LAST:event_btn_yenikayit1ActionPerformed

    private void btn_kaydet1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kaydet1ActionPerformed
        if((txt_id2.getText()).equals("")){
            try
            {
                conn=db.connet_db();
                String sql="INSERT INTO UYELER(AD_SOYAD,E_MAIL,ADRES,TEL,TEL2,EHLIYET_YIL) VALUES(?,?,?,?,?,?)";
                pst=conn.prepareStatement(sql);
                pst.setString(1, txt_adsoyad.getText());
                pst.setString(2, txt_email.getText());
                pst.setString(3, txt_adres.getText());
                pst.setString(4, txt_tel.getText());
                pst.setString(5, txt_tel2.getText());
                pst.setString(6, txt_ehliyetyil.getText());
                pst.execute();
                retrievetable(jTableuye1,"SELECT * FROM UYELER");
                txtresetle();

            }
            catch(Exception ex)
            {

            }
            finally
            {
                try
                {
                    conn.close();
                }
                catch(Exception ex)
                {

                }
            }
        }
    }//GEN-LAST:event_btn_kaydet1ActionPerformed

    private void txt_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_emailActionPerformed

    private void txt_adresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_adresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_adresActionPerformed

    private void txt_telActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_telActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_telActionPerformed

    private void txt_ehliyetyilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ehliyetyilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ehliyetyilActionPerformed

    private void txt_tel2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tel2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_tel2ActionPerformed

    private void txt_id2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_id2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_id2ActionPerformed

    private void txt_adsoyadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_adsoyadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_adsoyadActionPerformed

    private void jTableuye1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableuye1MouseClicked
        String[] data=new String[columnsNumber];
        for (int j = 0; j < data.length; j++) {
            data[j]=jTableuye1.getValueAt(jTableuye1.getSelectedRow(), j).toString();
        }
        txt_id2.setText(data[0]);
        txt_adsoyad.setText(data[1]);
        txt_email.setText(data[2]);
        txt_adres.setText(data[3]);
        txt_tel.setText(data[4]);
        txt_tel2.setText(data[5]);
        txt_ehliyetyil.setText(data[6]);
    }//GEN-LAST:event_jTableuye1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        menu frame=new menu();frame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       menu frame=new menu();frame.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       menu frame=new menu();frame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_guncelle;
    private javax.swing.JButton btn_guncelle1;
    private javax.swing.JButton btn_güncelle2;
    private javax.swing.JButton btn_kaydet;
    private javax.swing.JButton btn_kaydet1;
    private javax.swing.JButton btn_kaydet2;
    private javax.swing.JButton btn_sil;
    private javax.swing.JButton btn_sil1;
    private javax.swing.JButton btn_sil2;
    private javax.swing.JButton btn_yenikayit;
    private javax.swing.JButton btn_yenikayit1;
    private javax.swing.JButton btn_yenikayıt2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTablearac;
    private javax.swing.JTable jTablecalisan;
    private javax.swing.JTable jTableuye1;
    private javax.swing.JLabel lbl_adres;
    private javax.swing.JLabel lbl_adsoyad;
    private javax.swing.JLabel lbl_ehliyetyil;
    private javax.swing.JLabel lbl_email;
    private javax.swing.JLabel lbl_id;
    private javax.swing.JLabel lbl_tel;
    private javax.swing.JLabel lbl_tel2;
    private javax.swing.JTextField txt_adres;
    private javax.swing.JTextField txt_adsoyad;
    private javax.swing.JTextField txt_adsoyad1;
    private javax.swing.JTextField txt_calisanID;
    private javax.swing.JTextField txt_durum;
    private javax.swing.JTextField txt_ehliyetyil;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_id2;
    private javax.swing.JTextField txt_kategori;
    private javax.swing.JTextField txt_kullaniciad;
    private javax.swing.JTextField txt_mail;
    private javax.swing.JTextField txt_marka;
    private javax.swing.JTextField txt_model;
    private javax.swing.JTextField txt_sifre;
    private javax.swing.JTextField txt_tel;
    private javax.swing.JTextField txt_tel2;
    private javax.swing.JTextField txt_telno;
    private javax.swing.JTextField txt_unvanid;
    private javax.swing.JTextField txt_vitestipi;
    private javax.swing.JTextField txt_yakittipi;
    // End of variables declaration//GEN-END:variables
}
