
import java.sql.*;
import java.time.LocalDate;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import com.itextpdf.text.Document;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileOutputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Date;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Pc
 */
public class system1 extends javax.swing.JFrame {

    /**
     * Creates new form system1
     */
    int toplam_gun; int t_ay; int t_gun; double  ara_fiyat,kdv,toplam_fiyat;
    Connection conn=null; PreparedStatement pst=null; ResultSet rs=null;
    double firstnum,secondnum,result;String operator;
    public system1() {
        initComponents();
    }

    void deger_ekle(javax.swing.JButton btn){
        String metin=txt_hesap.getText();
        metin +=btn.getText();
        txt_hesap.setText(metin);
    }
    void operator_islem(String islem){
        operator=islem;
        firstnum=Double.parseDouble(txt_hesap.getText());
        txt_hesap.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_etay = new javax.swing.JTextField();
        txt_etgun = new javax.swing.JTextField();
        txt_etyil = new javax.swing.JTextField();
        txt_algun = new javax.swing.JTextField();
        txt_alay = new javax.swing.JTextField();
        txt_alyil = new javax.swing.JTextField();
        txt_aracid = new javax.swing.JTextField();
        txt_uyeıd = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        t_areafatura = new javax.swing.JTextArea();
        jPanel7 = new javax.swing.JPanel();
        txt_hesap = new javax.swing.JTextField();
        btn_cıkarma = new javax.swing.JButton();
        btn_9 = new javax.swing.JButton();
        btn_8 = new javax.swing.JButton();
        btn_7 = new javax.swing.JButton();
        btn_carpma = new javax.swing.JButton();
        btn_4 = new javax.swing.JButton();
        btn_5 = new javax.swing.JButton();
        btn_6 = new javax.swing.JButton();
        btn_bolme = new javax.swing.JButton();
        btn_1 = new javax.swing.JButton();
        btn_2 = new javax.swing.JButton();
        btn_3 = new javax.swing.JButton();
        btn_mod = new javax.swing.JButton();
        btn_zero = new javax.swing.JButton();
        btn_dot = new javax.swing.JButton();
        btn_esittir = new javax.swing.JButton();
        btn_toplama = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        btn_del = new javax.swing.JButton();
        btn_c = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        lbl_aratoplam = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lbl_kdv = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lbl_toplam = new javax.swing.JLabel();
        btn_toplam = new javax.swing.JButton();
        btn_sil = new javax.swing.JButton();
        btn_fatura = new javax.swing.JButton();
        btn_kapat = new javax.swing.JButton();
        btn_reset = new javax.swing.JButton();
        btn_pdf = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_taracid = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setText("ARAÇ ID :");
        jLabel21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel22.setText("ÜYE ID:");
        jLabel22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("TESLİM ALINAN TARİH:");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("TESLİM EDİLEN TARİH :");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        txt_etay.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_etay.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        txt_etay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_etayActionPerformed(evt);
            }
        });

        txt_etgun.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_etgun.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        txt_etgun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_etgunActionPerformed(evt);
            }
        });

        txt_etyil.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_etyil.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        txt_etyil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_etyilActionPerformed(evt);
            }
        });

        txt_algun.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_algun.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        txt_algun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_algunActionPerformed(evt);
            }
        });

        txt_alay.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_alay.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        txt_alay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_alayActionPerformed(evt);
            }
        });

        txt_alyil.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_alyil.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        txt_alyil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_alyilActionPerformed(evt);
            }
        });

        txt_aracid.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_aracid.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        txt_uyeıd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_uyeıd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_uyeıd, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                    .addComponent(txt_aracid))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_etgun)
                    .addComponent(txt_algun, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(txt_etay, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_etyil, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txt_alay, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_alyil, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txt_aracid, txt_uyeıd});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel3, jLabel4});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(txt_uyeıd)
                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_etgun)
                    .addComponent(txt_etay)
                    .addComponent(txt_etyil, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_aracid, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_algun, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_alay, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_alyil, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel3, jLabel4});

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        t_areafatura.setColumns(20);
        t_areafatura.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        t_areafatura.setRows(5);
        jScrollPane1.setViewportView(t_areafatura);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 693, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("FATURA", jPanel6);

        jPanel7.setBackground(new java.awt.Color(153, 153, 153));
        jPanel7.setLayout(null);

        txt_hesap.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_hesap.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        txt_hesap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_hesapActionPerformed(evt);
            }
        });
        jPanel7.add(txt_hesap);
        txt_hesap.setBounds(12, 13, 462, 49);

        btn_cıkarma.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_cıkarma.setText("-");
        btn_cıkarma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cıkarmaActionPerformed(evt);
            }
        });
        jPanel7.add(btn_cıkarma);
        btn_cıkarma.setBounds(381, 211, 93, 87);

        btn_9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_9.setText("9");
        btn_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_9ActionPerformed(evt);
            }
        });
        jPanel7.add(btn_9);
        btn_9.setBounds(261, 211, 93, 87);

        btn_8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_8.setText("8");
        btn_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_8ActionPerformed(evt);
            }
        });
        jPanel7.add(btn_8);
        btn_8.setBounds(128, 211, 93, 87);

        btn_7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_7.setText("7");
        btn_7.setPreferredSize(new java.awt.Dimension(90, 90));
        btn_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_7ActionPerformed(evt);
            }
        });
        jPanel7.add(btn_7);
        btn_7.setBounds(12, 211, 93, 87);

        btn_carpma.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_carpma.setText("*");
        btn_carpma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_carpmaActionPerformed(evt);
            }
        });
        jPanel7.add(btn_carpma);
        btn_carpma.setBounds(381, 324, 93, 87);

        btn_4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_4.setText("4");
        btn_4.setPreferredSize(new java.awt.Dimension(90, 90));
        btn_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_4ActionPerformed(evt);
            }
        });
        jPanel7.add(btn_4);
        btn_4.setBounds(12, 324, 93, 87);

        btn_5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_5.setText("5");
        btn_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_5ActionPerformed(evt);
            }
        });
        jPanel7.add(btn_5);
        btn_5.setBounds(128, 324, 93, 87);

        btn_6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_6.setText("6");
        btn_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_6ActionPerformed(evt);
            }
        });
        jPanel7.add(btn_6);
        btn_6.setBounds(261, 324, 93, 87);

        btn_bolme.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_bolme.setText("/");
        btn_bolme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bolmeActionPerformed(evt);
            }
        });
        jPanel7.add(btn_bolme);
        btn_bolme.setBounds(381, 437, 93, 87);

        btn_1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_1.setText("1");
        btn_1.setPreferredSize(new java.awt.Dimension(90, 90));
        btn_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_1ActionPerformed(evt);
            }
        });
        jPanel7.add(btn_1);
        btn_1.setBounds(12, 437, 93, 87);

        btn_2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_2.setText("2");
        btn_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_2ActionPerformed(evt);
            }
        });
        jPanel7.add(btn_2);
        btn_2.setBounds(128, 437, 93, 87);

        btn_3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_3.setText("3");
        btn_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_3ActionPerformed(evt);
            }
        });
        jPanel7.add(btn_3);
        btn_3.setBounds(261, 437, 93, 87);

        btn_mod.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_mod.setText("MOD");
        btn_mod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modActionPerformed(evt);
            }
        });
        jPanel7.add(btn_mod);
        btn_mod.setBounds(381, 555, 93, 87);

        btn_zero.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_zero.setText("0");
        btn_zero.setPreferredSize(new java.awt.Dimension(90, 90));
        btn_zero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_zeroActionPerformed(evt);
            }
        });
        jPanel7.add(btn_zero);
        btn_zero.setBounds(12, 555, 93, 87);

        btn_dot.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_dot.setText(".");
        btn_dot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dotActionPerformed(evt);
            }
        });
        jPanel7.add(btn_dot);
        btn_dot.setBounds(128, 555, 93, 87);

        btn_esittir.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_esittir.setText("=");
        btn_esittir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_esittirActionPerformed(evt);
            }
        });
        jPanel7.add(btn_esittir);
        btn_esittir.setBounds(261, 555, 93, 87);

        btn_toplama.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_toplama.setText("+");
        btn_toplama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_toplamaActionPerformed(evt);
            }
        });
        jPanel7.add(btn_toplama);
        btn_toplama.setBounds(381, 101, 93, 87);

        jButton18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton18.setText("+/-");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton18);
        jButton18.setBounds(261, 101, 93, 87);

        btn_del.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_del.setText("DEL");
        btn_del.setPreferredSize(new java.awt.Dimension(90, 90));
        btn_del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_delActionPerformed(evt);
            }
        });
        jPanel7.add(btn_del);
        btn_del.setBounds(12, 101, 93, 87);

        btn_c.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_c.setText("C");
        btn_c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cActionPerformed(evt);
            }
        });
        jPanel7.add(btn_c);
        btn_c.setBounds(128, 101, 93, 87);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/empoleye/hesap mak.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        jPanel7.add(jLabel5);
        jLabel5.setBounds(0, 0, 490, 700);

        jTabbedPane2.addTab("HESAP MAKİNESİ", jPanel7);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setText("BGM RENT A CAR ");

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("ARA TOPLAM:");
        jLabel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        lbl_aratoplam.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_aratoplam.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("KDV:");
        jLabel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        lbl_kdv.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_kdv.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("TOPLAM:");
        jLabel16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        lbl_toplam.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_toplam.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        btn_toplam.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_toplam.setText("TOPLAM");
        btn_toplam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_toplamActionPerformed(evt);
            }
        });

        btn_sil.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_sil.setText("SİL");
        btn_sil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_silActionPerformed(evt);
            }
        });

        btn_fatura.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_fatura.setText("FATURA");
        btn_fatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_faturaActionPerformed(evt);
            }
        });

        btn_kapat.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_kapat.setText("KAPAT");
        btn_kapat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kapatActionPerformed(evt);
            }
        });

        btn_reset.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_reset.setText("RESET");
        btn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetActionPerformed(evt);
            }
        });

        btn_pdf.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_pdf.setText("PDF");
        btn_pdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pdfActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_toplam, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_fatura, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_pdf, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(btn_sil)
                        .addGap(30, 30, 30)
                        .addComponent(btn_kapat)
                        .addGap(18, 18, 18)
                        .addComponent(btn_reset, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(lbl_kdv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(lbl_aratoplam, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lbl_toplam, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(22, 36, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btn_fatura, btn_kapat, btn_pdf, btn_reset, btn_sil, btn_toplam});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_aratoplam, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_kdv, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_toplam, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_fatura, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_toplam, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_pdf, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_sil, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_kapat)
                    .addComponent(btn_reset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btn_fatura, btn_kapat, btn_pdf, btn_reset, btn_sil, btn_toplam});

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("TESLİM ALINACAK ARAÇ ID");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        txt_taracid.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_taracid.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/empoleye/update icon.png"))); // NOI18N
        jButton1.setText("TESLİM ALINDI");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(195, 195, 195)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txt_taracid, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(227, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(286, 286, 286))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_taracid, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/empoleye/icons8-back-arrow-50.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(411, 411, 411))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(14, 14, 14)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_etayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_etayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_etayActionPerformed

    private void txt_etgunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_etgunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_etgunActionPerformed

    private void txt_etyilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_etyilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_etyilActionPerformed

    private void txt_algunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_algunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_algunActionPerformed

    private void txt_alayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_alayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_alayActionPerformed

    private void txt_alyilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_alyilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_alyilActionPerformed
String a;
    private void btn_toplamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_toplamActionPerformed
       int sayac=0;
        try
       {
           int etgun1=Integer.parseInt(txt_etgun.getText());
           int etay1=Integer.parseInt(txt_etay.getText());
           int etyil1=Integer.parseInt(txt_etyil.getText());
           int algun1=Integer.parseInt(txt_algun.getText());
           int alay1=Integer.parseInt(txt_alay.getText());
           int alyil1=Integer.parseInt(txt_alyil.getText());
           int aracid=Integer.parseInt(txt_aracid.getText());
           conn=db.connet_db();
           String sql="SELECT * FROM ARAC WHERE ARAC_ID='"+aracid+"'";
           pst=conn.prepareStatement(sql);  
           rs=pst.executeQuery();
           int uye1=Integer.parseInt(txt_uyeıd.getText());
           String uye2 =txt_uyeıd.getText();
           if(uye2=="")
           {
               sayac++;
           }
        
           
           if(alyil1<2021||etyil1<2021||alay1<1||alay1>12||etay1<1||etay1>12||algun1<1||algun1>31
                   ||etgun1<1||etgun1>31)
           {   JOptionPane.showMessageDialog(null,"Lütfen geçerli tarih girişi yapınız!");
               sayac++;
           }
        toplam_gun=(alyil1*365+alay1*30+algun1)-(etyil1*365+etay1*30+etgun1);
           if(toplam_gun>0){
               t_ay=toplam_gun/30;
               t_gun=toplam_gun-t_ay*30;
           }
           else{
              JOptionPane.showMessageDialog(null, "Hatalı tarih girişi yaptınız!");
              sayac++;
           }
           
         a=rs.getString("KATEGORI_ID");
       
       }
       catch(Exception ex)
       {
           JOptionPane.showMessageDialog(null, "Hatalı Giriş! Kontrol Ediniz.");
           sayac++;
       }
       finally{
           try{
               conn.close();
               conn=db.connet_db();
               String sql="SELECT * FROM KATEGORI WHERE KATEGORI_ID='"+a+"'";
           pst=conn.prepareStatement(sql);
           rs=pst.executeQuery();
           
           if (rs.next() && sayac==0) {
           int b=Integer.parseInt(rs.getString("GUNLUK_FIYAT"));
           int c=Integer.parseInt(rs.getString("AYLIK_FIYAT"));
           ara_fiyat = t_gun*b+t_ay*c;
           kdv= ara_fiyat*0.18;
           toplam_fiyat=ara_fiyat+kdv;
           lbl_aratoplam.setText(String.format( "%.2f TL" , ara_fiyat));
           lbl_kdv.setText(String.format( "%.2f TL" , kdv));
           lbl_toplam.setText(String.format( "%.2f TL" , toplam_fiyat));
                
            }
             
           }
           catch(Exception ex)
           {
               
           }
           finally{
               try{
                   conn.close();
               }
               catch(Exception ex)
               {
                   
               }
           }
       }
    }//GEN-LAST:event_btn_toplamActionPerformed

    private void txt_hesapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_hesapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_hesapActionPerformed

    private void btn_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_1ActionPerformed
        deger_ekle(btn_1);
    }//GEN-LAST:event_btn_1ActionPerformed

    private void btn_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_2ActionPerformed
        deger_ekle(btn_2);
    }//GEN-LAST:event_btn_2ActionPerformed

    private void btn_esittirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_esittirActionPerformed
        secondnum=Double.parseDouble(txt_hesap.getText());
        if(operator=="Toplama"){
            result=firstnum+secondnum;
            txt_hesap.setText(String.valueOf(result));
        }
        else if(operator=="Çıkarma"){
            result=firstnum-secondnum;
            txt_hesap.setText(String.valueOf(result));
        }
        else if(operator=="Çarpma"){
            result=firstnum*secondnum;
            txt_hesap.setText(String.valueOf(result));
        }
        else if(operator=="Bölme"){
            result=firstnum/secondnum;
            txt_hesap.setText(String.valueOf(result));
        }
        else if(operator=="MOD"){
            result=firstnum%secondnum;
            txt_hesap.setText(String.valueOf(result));
        }
    }//GEN-LAST:event_btn_esittirActionPerformed

    private void btn_zeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_zeroActionPerformed
        deger_ekle(btn_zero);
    }//GEN-LAST:event_btn_zeroActionPerformed

    private void btn_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_3ActionPerformed
        deger_ekle(btn_3);
    }//GEN-LAST:event_btn_3ActionPerformed

    private void btn_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_4ActionPerformed
        deger_ekle(btn_4);
    }//GEN-LAST:event_btn_4ActionPerformed

    private void btn_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_5ActionPerformed
       deger_ekle(btn_5);
    }//GEN-LAST:event_btn_5ActionPerformed

    private void btn_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_6ActionPerformed
        deger_ekle(btn_6);
    }//GEN-LAST:event_btn_6ActionPerformed

    private void btn_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_7ActionPerformed
        deger_ekle(btn_7);
    }//GEN-LAST:event_btn_7ActionPerformed

    private void btn_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_8ActionPerformed
        deger_ekle(btn_8);
    }//GEN-LAST:event_btn_8ActionPerformed

    private void btn_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_9ActionPerformed
        deger_ekle(btn_9);
    }//GEN-LAST:event_btn_9ActionPerformed

    private void btn_toplamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_toplamaActionPerformed
        operator_islem("Toplama");
    }//GEN-LAST:event_btn_toplamaActionPerformed

    private void btn_cıkarmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cıkarmaActionPerformed
       operator_islem("Çıkarma");
    }//GEN-LAST:event_btn_cıkarmaActionPerformed

    private void btn_carpmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_carpmaActionPerformed
        operator_islem("Çarpma");
    }//GEN-LAST:event_btn_carpmaActionPerformed

    private void btn_bolmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bolmeActionPerformed
        operator_islem("Bölme");
    }//GEN-LAST:event_btn_bolmeActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton18ActionPerformed

    private void btn_cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cActionPerformed
        txt_hesap.setText("");
        firstnum=0;
        secondnum=0;
        operator=" ";
        result=0; 
    }//GEN-LAST:event_btn_cActionPerformed

    private void btn_modActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modActionPerformed
        operator_islem("MOD");
    }//GEN-LAST:event_btn_modActionPerformed

    private void btn_dotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dotActionPerformed
        StringBuffer stb=new StringBuffer(txt_hesap.getText());
        if(stb.indexOf(".")==-1){//nokta yoksa
            stb.append(".");
            txt_hesap.setText(stb.toString());
        }
    }//GEN-LAST:event_btn_dotActionPerformed

    private void btn_delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_delActionPerformed
        try{    
        StringBuffer stb=new StringBuffer(txt_hesap.getText());
        int index = stb.length()-1;//son index değeri
        stb.deleteCharAt(index);
        txt_hesap.setText(stb.toString());
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, "Silinecek değer bulunmamakta!");
        }    
    }//GEN-LAST:event_btn_delActionPerformed

    private void btn_silActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_silActionPerformed
      String data=t_areafatura.getText().trim();
        if(!data.equals(""))
        {    
            try
            {
                conn=db.connet_db();
                String sql="DELETE FROM ISLEMLER WHERE ISLEMLER_ID=(SELECT MAX(ISLEMLER_ID) FROM ISLEMLER)";
                pst=conn.prepareStatement(sql);
                pst.execute();
                JOptionPane.showMessageDialog(null, "Son kayıt silinmiştir!");
            }
            catch(Exception ex)
            {
                        
            }
            finally
            {
                try
                {
                    conn.close();
                }
                catch(Exception ex)
                {
                            
                }
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Fatura hesaplanmadan silinmez !");
        }
                      
    }//GEN-LAST:event_btn_silActionPerformed
 
    int durum;
    private void durumal(String aracid)
    {
        try
        {
            conn = db.connet_db();
            String sql = "SELECT * FROM ARAC WHERE ARAC_ID='"+aracid+"'";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            durum = Integer.parseInt(rs.getString("DURUM")); 
            
        }
        catch(Exception ex)
        {
            
        }
        finally
        {
            try
            {
                conn.close();
            }
            catch(Exception ex)
            {
                
            }
        }
    }

    
    
    private void btn_faturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_faturaActionPerformed
        durumal(txt_aracid.getText()); 
        if (durum==1) {
            if(lbl_toplam.getText().length()>0){
            t_areafatura.append(
                    "BGM RENT A CAR SYSTEM: \n\n"+
                    "Fatura Tarihi: \t"+ LocalDate.now() +
                    "\nArac ID: \t"+txt_aracid.getText()+
                    "\n Uye ID: \t"+txt_uyeıd.getText()+
                    "\n Teslim Edilen Tarih \t"+txt_etgun.getText()+"/"+txt_etay.getText()+"/"+txt_etyil.getText()+
                    "\n Teslim Alınacak Tarih \t"+txt_algun.getText()+"/"+txt_alay.getText()+"/"+txt_alyil.getText()+
                    "\n Ara Toplam Fiyat: \t"+ lbl_aratoplam.getText()+
                    "\nKDV: \t"+lbl_kdv.getText()+
                    "\nGenel Toplam: \t"+lbl_toplam.getText()+
            
                    "\n NOT:LÜTFEN ARACIN TESLİM EDİLECEĞİ GÜN SAAT: 17.00'DAN ÖNCE BAYİMİZE TESLİM EDİNİZ!\t"
            ); 
            String teslimettarih=txt_etgun.getText()+"/"+txt_etay.getText()+"/"+txt_etyil.getText();
            String teslimaltarih=txt_algun.getText()+"/"+txt_alay.getText()+"/"+txt_alyil.getText();
            
            try
            {
                conn = db.connet_db();
                String sql = "INSERT INTO ISLEMLER (UYE_ID,ARAC_ID,TEDILEN_TARIH,TALINAN_TARIH,KDV,ARA_TOPLAM,TOPLAM)"+
                             " VALUES('"+txt_uyeıd.getText()+"','"+txt_aracid.getText()+"','"+teslimettarih+"','"+
                       teslimaltarih+"','"+kdv+"','"+ara_fiyat+"','"+toplam_fiyat+"')";
                pst = conn.prepareStatement(sql);
                pst.execute(); // select sorgusu olmadığı için resultset rs'ye aktarılmaz; ve execute()
            }
            catch(Exception ex)
            {
                JOptionPane.showMessageDialog(null, ex);
            }
            finally
            {
                try
                {
                    conn.close();
                    conn = db.connet_db();
                    String sql = "UPDATE ARAC SET DURUM='0' WHERE ARAC_ID='"+txt_aracid.getText()+"'";

                    pst = conn.prepareStatement(sql);
                    pst.execute();

                }
                catch(Exception ex)
                {
                
                }
                finally{
                    try{
                        conn.close();
                    }
                    catch(Exception ex){
                        
                    }
                }
            }
            
            
          }
          else
          {
              JOptionPane.showMessageDialog(null, "Lütfen toplamı hesaplattırınız!");
          }}
        else{
             JOptionPane.showMessageDialog(null, "Seçtiğiniz tarihlerde araç uygun değildir!");
        }
    }//GEN-LAST:event_btn_faturaActionPerformed

    private void btn_kapatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kapatActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btn_kapatActionPerformed

    private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetActionPerformed
        txt_uyeıd.setText("");txt_aracid.setText("");txt_etgun.setText("");txt_etay.setText("");
       txt_etyil.setText("");txt_algun.setText("");txt_alay.setText("");txt_alyil.setText("");
       lbl_aratoplam.setText("");lbl_kdv.setText("");lbl_toplam.setText("");
        txt_taracid.setText("");
        t_areafatura.setText("");
       
      
    }//GEN-LAST:event_btn_resetActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            try
            {
                conn=db.connet_db();
                String sql="UPDATE ARAC SET DURUM='1' WHERE ARAC_ID='"+txt_taracid.getText()+"'";
                    pst=conn.prepareStatement(sql);
                   pst.execute();
                    JOptionPane.showMessageDialog(null, "Durum güncellenmiştir!");

            }
            catch(Exception ex)
            {
                
            }
            finally{
                try {
                    conn.close();
                } catch (Exception ex) {
                   
                }
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_pdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pdfActionPerformed
        if(t_areafatura.getText().length()>0) {
        LocalDate value= LocalDate.now() ;
        String value0=txt_aracid.getText();
        String value1= txt_uyeıd.getText();
        String value2= txt_etgun.getText();
        String value3 =txt_etay.getText();
        String value4= txt_etyil.getText();
        String value5=txt_algun.getText();
        String value6=txt_alay.getText();
        String value7=txt_alyil.getText();
        String value8= lbl_aratoplam.getText();
        String value9=lbl_kdv.getText();
        String value10=lbl_toplam.getText();
        String filePath = null;
        JFileChooser dialog = new JFileChooser();
        dialog.setSelectedFile(new File(value+"_"+value0+"_"+value1+"rentacar"+".pdf"));
            int dialogResult = dialog.showSaveDialog(null);
            if (dialogResult==JFileChooser.APPROVE_OPTION){
             filePath = dialog.getSelectedFile().getPath();
            }
                 
        try {
            Document myDocument = new Document();
        
           PdfWriter myWriter = PdfWriter.getInstance(myDocument, new FileOutputStream(filePath));
           myDocument.open();
           
           myDocument.add(new Paragraph("FATURA",FontFactory.getFont(FontFactory.TIMES_BOLD,20,Font.BOLD )));
           myDocument.add(new Paragraph(new Date().toString()));
           myDocument.add(new Paragraph("-------------------------------------------------------------------------------------------"));
           myDocument.add((new Paragraph("TARIH: " +value,FontFactory.getFont(FontFactory.TIMES_ROMAN,15,Font.PLAIN))));
           myDocument.add((new Paragraph("ARAC ID: "+value0,FontFactory.getFont(FontFactory.TIMES_ROMAN,15,Font.PLAIN))));
           myDocument.add((new Paragraph("UYE ID: "+value1,FontFactory.getFont(FontFactory.TIMES_ROMAN,15,Font.PLAIN))));
           myDocument.add(new Paragraph("-------------------------------------------------------------------------------------------"));
           myDocument.add(new Paragraph("TESLIM VERILEN TARIH:"+value2+"/"+value3+"/"+value4,FontFactory.getFont(FontFactory.TIMES_ROMAN,15,Font.PLAIN)));
           myDocument.add(new Paragraph("TESLIM ALINAN TARIH:"+value5+"/"+value6+"/"+value7,FontFactory.getFont(FontFactory.TIMES_ROMAN,15,Font.PLAIN)));
           myDocument.add(new Paragraph("ARA TOPLAM:"+value8,FontFactory.getFont(FontFactory.TIMES_ROMAN,15,Font.PLAIN)));
           myDocument.add(new Paragraph("KDV:"+value9,FontFactory.getFont(FontFactory.TIMES_ROMAN,15,Font.PLAIN)));
           myDocument.add(new Paragraph("TOPLAM:"+value10,FontFactory.getFont(FontFactory.TIMES_ROMAN,15,Font.PLAIN)));
           myDocument.add(new Paragraph("-------------------------------------------------------------------------------------------"));
           
           myDocument.add(new Paragraph("NOT:LUTFEN ARACIN TESLIM EDILECEGI GUN SAAT:17.00'DAN ONCE BAYIMIZE TESLIM EDINIZ!",FontFactory.getFont(FontFactory.TIMES_BOLD,15,Font.BOLD)));
           
           myDocument.newPage();
           myDocument.close();  
           JOptionPane.showMessageDialog(null,"PDF KAYIT EDİLDİ!");
            }
        
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
          }
          finally {
            
            try{
               rs.close();
               pst.close();
                
            }
            catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
         
            }
            }
            }
        else{
            JOptionPane.showMessageDialog(null,"PDF'E DÖNÜŞTÜRMEDEN ÖNCE FATURA HESAPLATTIRMALISINIZ!");
        
    }
    }//GEN-LAST:event_btn_pdfActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        menu frame=new menu();frame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(system1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(system1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(system1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(system1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new system1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_1;
    private javax.swing.JButton btn_2;
    private javax.swing.JButton btn_3;
    private javax.swing.JButton btn_4;
    private javax.swing.JButton btn_5;
    private javax.swing.JButton btn_6;
    private javax.swing.JButton btn_7;
    private javax.swing.JButton btn_8;
    private javax.swing.JButton btn_9;
    private javax.swing.JButton btn_bolme;
    private javax.swing.JButton btn_c;
    private javax.swing.JButton btn_carpma;
    private javax.swing.JButton btn_cıkarma;
    private javax.swing.JButton btn_del;
    private javax.swing.JButton btn_dot;
    private javax.swing.JButton btn_esittir;
    private javax.swing.JButton btn_fatura;
    private javax.swing.JButton btn_kapat;
    private javax.swing.JButton btn_mod;
    private javax.swing.JButton btn_pdf;
    private javax.swing.JButton btn_reset;
    private javax.swing.JButton btn_sil;
    private javax.swing.JButton btn_toplam;
    private javax.swing.JButton btn_toplama;
    private javax.swing.JButton btn_zero;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JLabel lbl_aratoplam;
    private javax.swing.JLabel lbl_kdv;
    private javax.swing.JLabel lbl_toplam;
    private javax.swing.JTextArea t_areafatura;
    private javax.swing.JTextField txt_alay;
    private javax.swing.JTextField txt_algun;
    private javax.swing.JTextField txt_alyil;
    private javax.swing.JTextField txt_aracid;
    private javax.swing.JTextField txt_etay;
    private javax.swing.JTextField txt_etgun;
    private javax.swing.JTextField txt_etyil;
    private javax.swing.JTextField txt_hesap;
    private javax.swing.JTextField txt_taracid;
    private javax.swing.JTextField txt_uyeıd;
    // End of variables declaration//GEN-END:variables
}
